import turtle

# Big base circle
turtle.penup()
turtle.goto(-40,-220)
turtle.pendown()
turtle.circle(110)

# Middle Circle
turtle.penup()
turtle.goto(-45,-30)
turtle.pendown()
turtle.color("white")
turtle.pencolor("black")
turtle.begin_fill()
turtle.circle(80)
turtle.end_fill()


# Top circle
turtle.penup()
turtle.goto(-40,110)
turtle.pendown()
turtle.color("white")
turtle.pencolor("black")
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()


# Eyes
turtle.penup()
turtle.goto(-50, 160)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()
turtle.penup()
turtle.goto(-20,160)
turtle.pendown()
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()

# Mouth
turtle.penup()
turtle.goto(-70, 140)
turtle.left(340)
turtle.width(10)
turtle.color("red")
turtle.pendown()
turtle.circle(90,40)

# Three buttons
turtle.penup()
turtle.goto(-40, -10)
turtle.pendown()
turtle.color("purple")
turtle.begin_fill()
turtle.circle(4)
turtle.end_fill()
turtle.penup()
turtle.goto(-40,30)
turtle.pendown()
turtle.begin_fill()
turtle.circle(4)
turtle.penup()
turtle.goto(-40,60)
turtle.pendown()
turtle.begin_fill()
turtle.circle(4)
turtle.end_fill()

# Hat
turtle.penup()
turtle.goto(-100,190)
turtle.pendown()
turtle.color("blue")
turtle.pencolor("green")
turtle.begin_fill()
turtle.left(-20)
turtle.forward(120)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(80)
turtle.left(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(20)
turtle.end_fill()


# Arms
turtle.penup()
turtle.goto(-90,90)
turtle.color("brown")
turtle.width(10)
turtle.right(80)
turtle.pendown()
turtle.forward(90)
turtle.back(25)
turtle.left(40)
turtle.forward(25)
turtle.back(25)
turtle.right(80)
turtle.forward(25)
turtle.penup()
turtle.goto(20,90)
turtle.right(80)
turtle.pendown()
turtle.forward(90)
turtle.back(25)
turtle.left(40)
turtle.forward(25)
turtle.back(25)
turtle.right(80)
turtle.forward(25)
turtle.hideturtle()

turtle.done()